# Cloud Build configuration for SEO Agent
# Builds and deploys to Cloud Run

steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/seo-agent:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/seo-agent:latest'
      - '.'

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/seo-agent:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/seo-agent:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'seo-agent'
      - '--image'
      - 'gcr.io/$PROJECT_ID/seo-agent:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300s'
      - '--concurrency'
      - '10'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '5'
      - '--set-env-vars'
      - 'NODE_ENV=production'

# Substitution variables (can be overridden)
substitutions:
  _REGION: 'us-central1'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY

# Store images
images:
  - 'gcr.io/$PROJECT_ID/seo-agent:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/seo-agent:latest'
