/**
 * PDF Report Generator for SEO Analysis
 * Uses pdfmake document-definition object for layout; no manual positioning.
 * Produces a professional PDF with scores, summary, metadata, CWV, Lighthouse,
 * recommendations, and detailed issues. Branding: SEO Agent • aidynesolutions.com
 */

import { createRequire } from 'node:module';
import path from 'node:path';
import type { SEOReport, SEOIssue } from './types.js';
import type { SiteAnalysisResult } from './site-analyzer.js';

// pdfmake document definition shape (no @types/pdfmake)
interface PdfMakeDocDef {
  pageSize?: string;
  pageMargins?: { left: number; right: number; top: number; bottom: number };
  defaultStyle?: Record<string, unknown>;
  header?: string | ((currentPage: number, pageCount: number, pageSize: object) => object);
  footer?: string | ((currentPage: number, pageCount: number, pageSize: object) => object);
  styles?: Record<string, Record<string, unknown>>;
  content?: unknown[];
}

const require = createRequire(import.meta.url);

// pdfmake is CJS; load it and configure fonts for Node
const pdfMake = require('pdfmake');
const pdfMakePkgDir = path.resolve(path.dirname(require.resolve('pdfmake')), '..');
const robotoDir = path.join(pdfMakePkgDir, 'fonts', 'Roboto');
pdfMake.addFonts({
  Roboto: {
    normal: path.join(robotoDir, 'Roboto-Regular.ttf'),
    bold: path.join(robotoDir, 'Roboto-Medium.ttf'),
    italics: path.join(robotoDir, 'Roboto-Italic.ttf'),
    bolditalics: path.join(robotoDir, 'Roboto-MediumItalic.ttf'),
  },
});

const REPORT_SOURCE_URL = 'https://aidynesolutions.com/';
const REPORT_SOURCE_LABEL = 'SEO Agent';

const COLORS = {
  primary: '#1a1a2e',
  sectionBg: '#0f3460',
  pass: '#10b981',
  fail: '#ef4444',
  warning: '#f59e0b',
  info: '#6366f1',
  text: '#1f2937',
  textMuted: '#6b7280',
  border: '#e5e7eb',
};

/** Builds the full SEO report PDF and returns a Buffer (pdfmake document definition) */
export function buildPdfReport(report: SEOReport): Promise<Buffer> {
  const docDef = buildDocumentDefinition(report);
  const pdfDoc = pdfMake.createPdf(docDef);
  return pdfDoc.getBuffer();
}

/**
 * Builds a site-wide SEO report PDF: lists all scrolled URLs and shows SEO info per page.
 */
export function buildPdfReportFromSite(siteReport: SiteAnalysisResult): Promise<Buffer> {
  const docDef = buildSiteDocumentDefinition(siteReport);
  const pdfDoc = pdfMake.createPdf(docDef);
  return pdfDoc.getBuffer();
}

/** Shared helper: build issue rows for a table from SEOIssue[] */
function buildIssueRows(issues: SEOIssue[]): unknown[][] {
  const header = [
    { text: 'Check', fillColor: COLORS.sectionBg, color: '#fff' },
    { text: 'Status', fillColor: COLORS.sectionBg, color: '#fff' },
    { text: 'Details', fillColor: COLORS.sectionBg, color: '#fff' },
  ];
  const categories = ['basic', 'intermediate', 'advanced'] as const;
  const rows: unknown[][] = [header];
  for (const category of categories) {
    const catIssues = issues.filter((i) => i.category === category);
    for (const issue of catIssues) {
      const statusIcon = issue.status === 'pass' ? '✓' : issue.status === 'fail' ? '✗' : issue.status === 'warning' ? '⚠' : 'ℹ';
      const statusColor = issue.status === 'pass' ? COLORS.pass : issue.status === 'fail' ? COLORS.fail : issue.status === 'warning' ? COLORS.warning : COLORS.info;
      const details: unknown[] = [issue.description];
      if (issue.currentValue) details.push(`Current: ${issue.currentValue}`);
      if (issue.status !== 'pass' && issue.recommendation) details.push(`→ ${issue.recommendation}`);
      if (issue.referenceUrl) details.push({ text: issue.referenceUrl, link: issue.referenceUrl, color: COLORS.info, fontSize: 7 });
      rows.push([
        `${statusIcon} ${issue.checkName}`,
        { text: issue.status, color: statusColor },
        { stack: details, fontSize: 8 },
      ]);
    }
  }
  return rows;
}

/** Builds the pdfmake document definition for a site-wide report */
function buildSiteDocumentDefinition(siteReport: SiteAnalysisResult): PdfMakeDocDef {
  const content: PdfMakeDocDef['content'] = [];

  // ---- Title ----
  content.push(
    { text: 'SEO Site Analysis Report', style: 'title', alignment: 'center' },
    {
      text: `Generated by ${REPORT_SOURCE_LABEL} • ${REPORT_SOURCE_URL}`,
      style: 'subtitle',
      alignment: 'center',
    },
    { text: ' ', margin: [0, 4] },
    { canvas: [{ type: 'line', x1: 0, y1: 0, x2: 515, y2: 0, lineWidth: 0.5, lineColor: COLORS.border }] },
    { text: ' ', margin: [0, 12] }
  );

  // ---- Base URL & date ----
  content.push({
    table: {
      widths: [120, '*'],
      body: [
        [{ text: 'Base URL:', bold: true }, { text: siteReport.baseUrl }],
        [{ text: 'Analysis Date:', bold: true }, { text: new Date(siteReport.analyzedAt).toLocaleString() }],
        [{ text: 'Depth:', bold: true }, { text: String(siteReport.depth) }],
        [
          { text: 'Crawl stats:', bold: true },
          {
            text: `${siteReport.crawlStats.totalCrawled} pages crawled, ${siteReport.crawlStats.failedPages} failed, ${(siteReport.crawlStats.crawlDuration / 1000).toFixed(1)}s`,
          },
        ],
      ],
    },
    layout: 'noBorders',
    margin: [0, 0, 0, 16],
  });

  // ---- Analyzed URLs (scrolled pages) ----
  content.push({ text: 'Analyzed URLs (pages in this report)', style: 'sectionHeader' });
  const urlListBody = siteReport.pageAnalyses.map((p, i) => [
    { text: `${i + 1}.`, width: 24 },
    { text: p.url, link: p.url, fontSize: 9 },
  ]);
  content.push({
    table: { widths: [24, '*'], body: urlListBody },
    layout: 'noBorders',
    margin: [0, 0, 0, 16],
  });

  // ---- Site-level scores ----
  content.push({ text: 'Site summary scores', style: 'sectionHeader' });
  const scoreLabels = ['Overall', 'Average page', 'Lowest page', 'Highest page'];
  const scoreValues = [
    siteReport.scores.overall,
    siteReport.scores.averagePageScore,
    siteReport.scores.lowestPageScore,
    siteReport.scores.highestPageScore,
  ];
  const scoreCells = scoreValues.map((score, i) => {
    const color = score >= 90 ? COLORS.pass : score >= 70 ? COLORS.info : score >= 50 ? COLORS.warning : COLORS.fail;
    return {
      table: {
        widths: [115],
        body: [
          [{ text: String(score), fillColor: color, color: '#fff', bold: true, fontSize: 14, alignment: 'center', margin: [0, 6] }],
          [{ text: scoreLabels[i], fillColor: color, color: '#fff', fontSize: 8, alignment: 'center', margin: [0, 4] }],
        ],
      },
      layout: 'noBorders',
    };
  });
  content.push({
    columns: scoreCells,
    columnGap: 10,
    margin: [0, 0, 0, 16],
  });

  // ---- Site recommendations (optional) ----
  if (siteReport.recommendations) {
    const recs = [
      { title: 'Critical', items: siteReport.recommendations.critical, color: COLORS.fail },
      { title: 'Important', items: siteReport.recommendations.important, color: COLORS.warning },
      { title: 'Suggestions', items: siteReport.recommendations.suggestions, color: COLORS.info },
    ];
    for (const { title, items, color } of recs) {
      if (items.length === 0) continue;
      content.push({ text: title, bold: true, color, margin: [0, 8, 0, 4] });
      content.push({ ul: items.slice(0, 10).map((item) => ({ text: item })), margin: [8, 0, 0, 0] });
      if (items.length > 10) content.push({ text: `… and ${items.length - 10} more`, italics: true, margin: [8, 4, 0, 0] });
      content.push({ text: ' ', margin: [0, 4] });
    }
  }

  // ---- Per-page SEO info ----
  content.push({ text: 'SEO details per page', style: 'sectionHeader' });
  for (let idx = 0; idx < siteReport.pageAnalyses.length; idx++) {
    const page = siteReport.pageAnalyses[idx];
    content.push({
      text: `Page ${idx + 1}: ${page.url}`,
      style: 'sectionHeader',
      fontSize: 11,
      margin: [0, idx === 0 ? 0 : 16, 0, 4],
    });
    content.push({
      text: `Score: ${page.score}/100  •  Critical: ${page.criticalCount}  •  Warnings: ${page.warningCount}`,
      fontSize: 9,
      color: COLORS.textMuted,
      margin: [0, 0, 0, 8],
    });
    const issueRows = buildIssueRows(page.issues);
    if (issueRows.length > 1) {
      content.push({
        table: { headerRows: 1, widths: [120, 70, '*'], body: issueRows },
        layout: 'lightHorizontalLines',
        margin: [0, 0, 0, 12],
      });
    } else {
      content.push({ text: 'No issues recorded for this page.', italics: true, margin: [0, 0, 0, 12] });
    }
  }

  const docDefinition: PdfMakeDocDef = {
    pageSize: 'A4',
    pageMargins: { left: 50, right: 50, top: 60, bottom: 60 },
    defaultStyle: {
      font: 'Roboto',
      fontSize: 10,
      color: COLORS.text,
    },
    header: () => ({
      text: `${REPORT_SOURCE_LABEL} — SEO Site Analysis Report`,
      style: 'header',
      margin: [50, 20, 50, 0],
    }),
    footer: (currentPage: number, pageCount: number) => ({
      text: `${REPORT_SOURCE_LABEL} | ${REPORT_SOURCE_URL} | Page ${currentPage} of ${pageCount}`,
      style: 'footer',
      alignment: 'center',
      margin: [50, 0, 50, 20],
    }),
    styles: {
      title: { fontSize: 24, bold: true, color: COLORS.primary },
      subtitle: { fontSize: 10, color: COLORS.textMuted },
      sectionHeader: { fontSize: 12, bold: true, color: COLORS.primary, margin: [0, 12, 0, 6] },
      header: { fontSize: 9, color: COLORS.textMuted },
      footer: { fontSize: 8, color: COLORS.textMuted },
    },
    content,
  };

  return docDefinition;
}

/** Builds the pdfmake document definition object from SEOReport */
function buildDocumentDefinition(report: SEOReport): PdfMakeDocDef {
  const content: PdfMakeDocDef['content'] = [];

  // ---- Title block ----
  content.push(
    { text: 'SEO Analysis Report', style: 'title', alignment: 'center' },
    {
      text: `Generated by ${REPORT_SOURCE_LABEL} • ${REPORT_SOURCE_URL}`,
      style: 'subtitle',
      alignment: 'center',
    },
    { text: ' ', margin: [0, 4] },
    { canvas: [{ type: 'line', x1: 0, y1: 0, x2: 515, y2: 0, lineWidth: 0.5, lineColor: COLORS.border }] },
    { text: ' ', margin: [0, 12] }
  );

  // ---- Analyzed URL & date (table for alignment) ----
  content.push({
    table: {
      widths: [120, '*'],
      body: [
        [{ text: 'Analyzed URL:', bold: true }, { text: report.url }],
        [{ text: 'Analysis Date:', bold: true }, { text: new Date(report.analyzedAt).toLocaleString() }],
        [{ text: 'Depth:', bold: true }, { text: String(report.depth) }],
      ],
    },
    layout: 'noBorders',
    margin: [0, 0, 0, 16],
  });

  // ---- Scores section ----
  content.push({ text: 'Scores', style: 'sectionHeader' });
  const scoreLabels = ['Overall', 'Basic', 'Intermediate', 'Advanced'];
  const scoreValues = [
    report.scores.overall,
    report.scores.basic,
    report.scores.intermediate,
    report.scores.advanced,
  ];
  const scoreCells = scoreValues.map((score, i) => {
    const color = score >= 90 ? COLORS.pass : score >= 70 ? COLORS.info : score >= 50 ? COLORS.warning : COLORS.fail;
    return {
      table: {
        widths: [115],
        body: [
          [{ text: String(score), fillColor: color, color: '#fff', bold: true, fontSize: 16, alignment: 'center', margin: [0, 8] }],
          [{ text: scoreLabels[i], fillColor: color, color: '#fff', fontSize: 8, alignment: 'center', margin: [0, 4] }],
        ],
      },
      layout: 'noBorders',
    };
  });
  content.push({
    columns: scoreCells,
    columnGap: 10,
    margin: [0, 0, 0, 16],
  });

  // ---- Summary ----
  content.push({ text: 'Summary', style: 'sectionHeader' });
  content.push({
    text: [
      { text: `Total checks: ${report.summary.totalChecks}  ` },
      { text: `Passed: ${report.summary.passed}  `, color: COLORS.pass },
      { text: `Failed: ${report.summary.failed}  `, color: COLORS.fail },
      { text: `Warnings: ${report.summary.warnings}`, color: COLORS.warning },
    ],
    margin: [0, 0, 0, 16],
  });

  // ---- Page metadata ----
  if (report.metadata) {
    content.push({ text: 'Page Metadata', style: 'sectionHeader' });
    const metaRows: (string | { text: string; bold?: boolean })[][] = [];
    if (report.metadata.title) {
      metaRows.push(['Title:', report.metadata.title]);
    }
    if (report.metadata.metaDescription) {
      metaRows.push(['Meta description:', report.metadata.metaDescription]);
    }
    if (report.metadata.canonical) {
      metaRows.push(['Canonical:', report.metadata.canonical]);
    }
    if (metaRows.length) {
      content.push({
        table: {
          widths: [100, '*'],
          body: metaRows.map(([label, value]) => [
            { text: label, bold: true },
            { text: String(value), fillColor: undefined },
          ]),
        },
        layout: 'noBorders',
        margin: [0, 0, 0, 16],
      });
    }
  }

  // ---- Core Web Vitals ----
  if (report.pageSpeed?.coreWebVitals) {
    content.push({ text: 'Core Web Vitals', style: 'sectionHeader' });
    const cwv = report.pageSpeed.coreWebVitals;
    const cwvEntries: [string, { value: number; rating: string; displayValue: string } | null][] = [
      ['LCP (Largest Contentful Paint)', cwv.lcp],
      ['CLS (Cumulative Layout Shift)', cwv.cls],
      ['INP (Interaction to Next Paint)', cwv.inp],
      ['FID (First Input Delay)', cwv.fid],
      ['TTFB (Time to First Byte)', cwv.ttfb],
    ];
    const cwvBody = cwvEntries
      .filter(([, m]) => m != null)
      .map(([label, metric]) => {
        const ratingColor =
          metric!.rating === 'good' ? COLORS.pass : metric!.rating === 'needs-improvement' ? COLORS.warning : COLORS.fail;
        return [{ text: label }, { text: metric!.displayValue, color: ratingColor }];
      });
    if (cwvBody.length) {
      content.push({
        table: { widths: ['*', 'auto'], body: cwvBody },
        layout: 'noBorders',
        margin: [0, 0, 0, 16],
      });
    }
  }

  // ---- Lighthouse scores ----
  if (report.pageSpeed?.lighthouseScores) {
    content.push({ text: 'Lighthouse Scores', style: 'sectionHeader' });
    const lh = report.pageSpeed.lighthouseScores;
    const lhBody: (string | number)[][] = [];
    [
      ['Performance', lh.performance],
      ['Accessibility', lh.accessibility],
      ['Best Practices', lh.bestPractices],
      ['SEO', lh.seo],
    ].forEach(([label, value]) => {
      if (value !== null) lhBody.push([String(label), `${value}/100`]);
    });
    if (report.pageSpeed.strategy) {
      lhBody.push(['Strategy', report.pageSpeed.strategy]);
    }
    if (lhBody.length) {
      content.push({
        table: { widths: ['*', 'auto'], body: lhBody },
        layout: 'noBorders',
        margin: [0, 0, 0, 16],
      });
    }
  }

  // ---- Recommendations ----
  if (report.recommendations) {
    const recs = [
      { title: 'Critical (fix now)', items: report.recommendations.critical, color: COLORS.fail },
      { title: 'Important (should fix)', items: report.recommendations.important, color: COLORS.warning },
      { title: 'Suggestions', items: report.recommendations.suggestions, color: COLORS.info },
    ];
    for (const { title, items, color } of recs) {
      if (items.length === 0) continue;
      content.push({ text: title, bold: true, color, margin: [0, 8, 0, 4] });
      content.push({
        ul: items.slice(0, 15).map((item) => ({ text: item })),
        margin: [8, 0, 0, 0],
      });
      if (items.length > 15) {
        content.push({ text: `… and ${items.length - 15} more`, italics: true, margin: [8, 4, 0, 0] });
      }
      content.push({ text: ' ', margin: [0, 4] });
    }
  }

  // ---- Detailed findings (table with repeating header) ----
  content.push({ text: 'Detailed Findings', style: 'sectionHeader' });
  const categories = ['basic', 'intermediate', 'advanced'] as const;
  const issueRows: unknown[][] = [
    [{ text: 'Check', fillColor: COLORS.sectionBg, color: '#fff' }, { text: 'Status', fillColor: COLORS.sectionBg, color: '#fff' }, { text: 'Details', fillColor: COLORS.sectionBg, color: '#fff' }],
  ];
  for (const category of categories) {
    const issues = report.issues.filter((i) => i.category === category);
    for (const issue of issues) {
      const statusIcon = issue.status === 'pass' ? '✓' : issue.status === 'fail' ? '✗' : issue.status === 'warning' ? '⚠' : 'ℹ';
      const statusColor = issue.status === 'pass' ? COLORS.pass : issue.status === 'fail' ? COLORS.fail : issue.status === 'warning' ? COLORS.warning : COLORS.info;
      const details: unknown[] = [issue.description];
      if (issue.currentValue) details.push(`Current: ${issue.currentValue}`);
      if (issue.status !== 'pass' && issue.recommendation) details.push(`→ ${issue.recommendation}`);
      if (issue.referenceUrl) details.push({ text: issue.referenceUrl, link: issue.referenceUrl, color: COLORS.info, fontSize: 7 });
      issueRows.push([
        `${statusIcon} ${issue.checkName}`,
        { text: issue.status, color: statusColor },
        { stack: details, fontSize: 8 },
      ]);
    }
  }
  if (issueRows.length > 1) {
    content.push({
      table: {
        headerRows: 1,
        widths: [120, 70, '*'],
        body: issueRows,
      },
      layout: 'lightHorizontalLines',
      margin: [0, 0, 0, 16],
    });
  }

  const docDefinition: PdfMakeDocDef = {
    pageSize: 'A4',
    pageMargins: { left: 50, right: 50, top: 60, bottom: 60 },
    defaultStyle: {
      font: 'Roboto',
      fontSize: 10,
      color: COLORS.text,
    },
    header: () => ({
      text: `${REPORT_SOURCE_LABEL} — SEO Analysis Report`,
      style: 'header',
      margin: [50, 20, 50, 0],
    }),
    footer: (currentPage: number, pageCount: number) => ({
      text: `${REPORT_SOURCE_LABEL} | ${REPORT_SOURCE_URL} | Page ${currentPage} of ${pageCount}`,
      style: 'footer',
      alignment: 'center',
      margin: [50, 0, 50, 20],
    }),
    styles: {
      title: { fontSize: 24, bold: true, color: COLORS.primary },
      subtitle: { fontSize: 10, color: COLORS.textMuted },
      sectionHeader: { fontSize: 12, bold: true, color: COLORS.primary, margin: [0, 12, 0, 6] },
      header: { fontSize: 9, color: COLORS.textMuted },
      footer: { fontSize: 8, color: COLORS.textMuted },
    },
    content,
  };

  return docDefinition;
}
